UI launches crawl
SD-2023-CS10/Project-Version-0 pull request #55
Opened 2024-02-26 02:01 UTC by colleenlemak11

2024-02-26 19:43 UTC, BrandonHuyck requested changes
See comments. Notable, 1) there seems to be some misunderstanding around the difference between database and application credentials; and 2) there needs to be more clarity with `printhi`.

2024-02-26 19:43 UTC, BrandonHuyck commented on crawler/README.md
> +1. Upon the repository tool's bootup, `login.html` prompts the user for their credentials.  This information is dynamically written to the UI's config.ini file for parsing and storage.
I'm not sure this is true. The login page should be for the user/pass for our app. The config file is for db credentials--these are not getting set dynamically in our current version ("Beyond scope").

2024-02-26 19:43 UTC, BrandonHuyck commented on UI/runScan.php
> +    // $username = $config["username"];
The username for our app is different from the username for the database. The database credentials (user/pass) are fixed; any sort of dynamic validation/setting is beyond our scope. The username that we are passing around through code and that the user inputs on the login screen is solely their user/pass for our app, which tells the DB what client they are associated with.

2024-02-26 19:43 UTC, BrandonHuyck commented on UI/runScan.php
> +    // Locate and parse configuration file
The config file only needs to be parsed when you are manually connecting to the database

2024-02-26 19:43 UTC, BrandonHuyck commented on UI/runScan.php
> +    // $username = $config["username"];
The username will be stored in a PHP `$_SESSION[<usr>]` variable. See: [link](https://www.w3schools.com/php/php_sessions.asp).

2024-02-26 19:43 UTC, BrandonHuyck commented on crawler/printhi.py
The purpose of this file is unclear. Also, the name should probably be changed, unless that is clarified with its purpose.

2024-02-26 19:43 UTC, BrandonHuyck commented on UI/runScan.php
> +        // $crawlerScriptRelativePath = '/../crawler/printhi.py';
Lines 66-67 are unclear to me.

2024-02-28 00:07 UTC, colleenlemak11 commented
Update to PR #55: 

Implements:
- POST request
- Changes to how username is received (NOT via config file)
- Changes to related integration documentation

Keeps:
- HTML requests
- proc_open() built-in method
- Piping process in runScan.py (to receive console messages)  

Notes:
I tried switching to the simpler logic wrapping the scan button in <form>, but I wasn't able to print any echo/print messages from the files (confirming they are actually running). Optimizing this code could be a post-demo task if we really want to get rid of console messages and/or the output-piping process.

Expected Sequence:
Button click -> runScan.php -> dependency-checks.php and crawl-device.py are launched.

2024-02-28 19:13 UTC, BrandonHuyck approved these changes

2024-02-28 19:13 UTC, merged