Added link for forgot PW, added page for forgot PW, added styling for…
SD-2023-CS10/Project-Version-0 pull request #86
Opened 2024-04-13 02:05 UTC by artisnate

Added link for forgot PW, added page for forgot PW, added styling for forgot PW page.

2024-04-15 21:36 UTC, JPNealon reviewed
looks good

2024-04-15 22:33 UTC, BrandonHuyck requested changes
Requesting uniform design for `login.html`

2024-04-15 22:33 UTC, BrandonHuyck commented on UI/login.html
Can we get a uniform design format for the three links? Having one a different color and underlined when the other two are not may not be the most visually appealing.

I tried to just change the `Change Password` styling but could not get it to work. One solution would be to have three rows, each link on its own, rather than two rows, with `Change Password` and `Forgot Password` on the same, but I did not try that, myself.

2024-04-16 19:35 UTC, BrandonHuyck approved these changes

2024-04-16 19:35 UTC, merged